package exception

import "fmt"

func test(){

	fmt.Println("exception!")
}
