package exception

import "fmt"

func tt(){

	fmt.Println("exception!")
}
